#!/usr/bin/env python3

import shutil, os

OUT_DIR = './public'
SRC_DIR = './src'
COPY = ['/js', '/css', '/font', '/asset', '/about.html', '/index.html', '/events.html']

class Hook:
    @staticmethod
    def pre():
        shutil.rmtree(OUT_DIR, ignore_errors=True)
        os.mkdir(OUT_DIR)
    def post():
        pass

def copy(src, dist) -> None:
    print("[COPY]", src, "->" , dist)
    if os.path.isfile(src):
        shutil.copy(src, dist)
    else:
        shutil.copytree(src, dist)

def main() -> None:
    for obj in COPY:
        copy(SRC_DIR + obj, OUT_DIR + obj)

if __name__ == '__main__':
    Hook.pre()
    exit(main() or 0)
    Hook.post()